language: node_js

sudo: false

notifications:
  email: false

node_js:
  - '7'

before_install:
  - export CHROME_BIN=chromium-browser
  

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start