import { BaseAppService } from './app/app.service';
export { BaseAppService } from './app/app.service';
import { BaseAppComponent } from './app/app.component';
export { BaseAppComponent } from './app/app.component';
import { BaseComponent } from './app/base.component';
export { BaseComponent } from './app/base.component';
import { BaseAppModule } from './app/app.module';
export { BaseAppModule } from './app/app.module';
import { BaseModule } from './app/base.module';
export { BaseModule } from './app/base.module';
export const TestServices = [BaseAppService];
